### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Pyro979** [shindakun/glitchup#1]
Would it be possible to add an optional path parameter. Something like this: glitchup("/refresh"); so that we can hit a certain route instead of the root?

**Comment by Pyro979** [comment]
Added a pull request. Thanks for a neat module =c)

**Comment by shindakun** [comment]
@Pyro979 not sure how I didn't see this earlier, apologies - I'll take a look at it today, thanks for the PR. 👍

**Comment by Pyro979** [comment]
hey, did this ever make it into NPM?

**Comment by shindakun** [comment]
@Pyro979 Swear I had published it but it seems I didn't. Just pushed it out again and it looks good now.
